//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecimalTime.Forms.i18n {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DecimalTime.Forms.i18n.AppStrings", typeof(AppStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        internal static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        internal static string lblBackgroundColor {
            get {
                return ResourceManager.GetString("lblBackgroundColor", resourceCulture);
            }
        }
        
        internal static string lblDateFormatLong {
            get {
                return ResourceManager.GetString("lblDateFormatLong", resourceCulture);
            }
        }
        
        internal static string lblDateFormatShort {
            get {
                return ResourceManager.GetString("lblDateFormatShort", resourceCulture);
            }
        }
        
        internal static string lblDateLabelColor {
            get {
                return ResourceManager.GetString("lblDateLabelColor", resourceCulture);
            }
        }
        
        internal static string lblEnableReaderOnDoubleTap {
            get {
                return ResourceManager.GetString("lblEnableReaderOnDoubleTap", resourceCulture);
            }
        }
        
        internal static string lblHoursHandColor {
            get {
                return ResourceManager.GetString("lblHoursHandColor", resourceCulture);
            }
        }
        
        internal static string lblMinutesHandColor {
            get {
                return ResourceManager.GetString("lblMinutesHandColor", resourceCulture);
            }
        }
        
        internal static string lblSecondsHandColor {
            get {
                return ResourceManager.GetString("lblSecondsHandColor", resourceCulture);
            }
        }
        
        internal static string lblSettingsPageTitle {
            get {
                return ResourceManager.GetString("lblSettingsPageTitle", resourceCulture);
            }
        }
        
        internal static string lblShowBackgroundImage {
            get {
                return ResourceManager.GetString("lblShowBackgroundImage", resourceCulture);
            }
        }
        
        internal static string lblTickMarksColor {
            get {
                return ResourceManager.GetString("lblTickMarksColor", resourceCulture);
            }
        }
    }
}
